"""공통 계약 — 주고받는 데이터 모델, 스키마 버전, 해시·서명 규칙 (C1~C14).

**원본은 하나다** (`docs/03-contracts/README.md` 원칙 1). 다른 앱은 이 패키지를 import하고,
복사본을 두지 않는다. 문서는 뜻·규칙·예시를 설명하고, 코드는 이 패키지가 전부다.

지금 구현된 것:

| 계약 | 모듈 | 내용 |
| --- | --- | --- |
| C1 | `manifest` | 패키지 매니페스트 + 검사 규칙 `validate()` |
| C2 | `hashing`, `signing` | `canonical_json`·`content_hash`, 서명 봉투 + 검증 규칙 V1~V8 |
| C3 | `events` | 실행 이벤트 (`kind`는 열린 문자열) |
| C4 | `bot_ui` | Bot UI 등록·하트비트 |
| C5 | `center_api` | 패키지·배포·작업 + 배포·작업 검사 |
| C6 | `approvals` | 결재 요청·답 + 폼으로 답 검증 |
| C7 | `resources`, `center_keys` | 리소스 목록 + 누락 검사, Center API 키 |
| C11 | `service_app` | 서비스 앱 공통 (manifest·작업 호출·키·멱등). 뼈대는 `chaeksas.service_kit` |
| C13 | `extension` | 확장 정의 + 검사 규칙 E1~E6. 호스트는 `chaeksas.core.extensions` |
| C14 | `bpmn_ext` | BPMN 확장 속성(`chk:*`) 모델 + BPMN 읽기 + 검사 B1~B14 + 시험 케이스 형식 |
| C14 | `dmn` | 규칙 태스크가 쓰는 DMN 결정표 읽기·판정 |
| C14 | `replay` | 재생 명세 (`memory/specs.json`, C1 패키지 구성) |

검사 함수가 계약마다 있어서, 이름이 겹치는 것은 루트에서 계약을 붙여 다시 내보낸다
(`validate_approval_create`, `validate_center_key_create`). 모듈 안의 이름은 계약 문서 그대로다.

자세히: docs/01-architecture.md §2, docs/03-contracts/.
"""

from chaeksas.contracts._base import (
    SEVERITY_ERROR,
    SEVERITY_WARNING,
    ContractModel,
    SchemaVersioned,
    Sha256,
    Timestamp,
    Violation,
)
from chaeksas.contracts.approvals import (
    AnswerRequest,
    ApprovalCreateRequest,
    ApprovalHost,
    ApprovalInfo,
    Form,
    FormField,
    apply_defaults,
    request_id_for,
    validate_answer,
)
from chaeksas.contracts.approvals import validate_create as validate_approval_create
from chaeksas.contracts.bot_ui import (
    ApprovalAck,
    ApprovalDispatch,
    CurrentRun,
    DeploymentResult,
    ExtensionState,
    HeartbeatRequest,
    HeartbeatResponse,
    JobAck,
    JobDispatch,
    Queue,
    QueueItem,
    Readiness,
    RegisterRequest,
    RegisterResponse,
    Runtimes,
    Versions,
    WorkerState,
)
from chaeksas.contracts.bpmn_ext import (
    BUILTIN_VARS,
    AiTask,
    Approval,
    BpmnProcess,
    BpmnReadError,
    Call,
    Case,
    CaseFile,
    CaseMessage,
    DataOutput,
    DecisionIo,
    Defaults,
    Email,
    ExtensionTask,
    FileList,
    InputDecl,
    Loop,
    ProcessInfo,
    Receive,
    Rule,
    ServiceCall,
    Webhook,
    available_vars,
    blocking,
    duration_hours,
    expression_vars,
    is_var_name,
    read_process,
)
from chaeksas.contracts.bpmn_ext import Flow as BpmnFlow
from chaeksas.contracts.bpmn_ext import Node as BpmnNode
from chaeksas.contracts.bpmn_ext import matches as matches_expected
from chaeksas.contracts.bpmn_ext import validate as validate_bpmn
from chaeksas.contracts.center_api import (
    BotUiInfo,
    BotUiKey,
    DeploymentInfo,
    ErrorBody,
    JobCreateRequest,
    JobInfo,
    JobTarget,
    ListParams,
    PackageInfo,
    PreflightSummary,
    cancel_outcome,
    validate_deployment,
    validate_job_create,
)
from chaeksas.contracts.center_keys import (
    BoundTo,
    CenterKeyCreated,
    CenterKeyCreateRequest,
    CenterKeyInfo,
    expires_soon,
)
from chaeksas.contracts.center_keys import key_state as center_key_state
from chaeksas.contracts.center_keys import prefix_of as center_key_prefix_of
from chaeksas.contracts.center_keys import validate_create as validate_center_key_create
from chaeksas.contracts.dmn import (
    Decision,
    DecisionInput,
    DecisionOutput,
    DecisionRule,
    DmnError,
    DmnReadError,
    decision_io,
    read_decisions,
)
from chaeksas.contracts.events import (
    EventBatchResponse,
    RejectedLine,
    RunEvent,
    RunEventsResponse,
    RunInfo,
    RunListing,
    missing_data_keys,
)
from chaeksas.contracts.extension import (
    AdapterAuth,
    AdapterHealth,
    AdapterLimits,
    AdapterOperation,
    AdapterRequest,
    AdapterResponse,
    Catalog,
    CatalogItem,
    ConfigurationItem,
    ConsolePage,
    Contributes,
    Editor,
    ErrorWhen,
    Executor,
    ExtensionManifest,
    HttpAdapter,
    KeyNeed,
    LocalRuntime,
    PreflightContribution,
    ResourceContribution,
    ResourceView,
    Service,
    StudioEditorContribution,
    TaskTypeContribution,
    Utility,
    definition_hash,
    task_type_conflicts,
    verify_external,
)
from chaeksas.contracts.extension import check_api as check_extension_api
from chaeksas.contracts.extension import check_size as check_extension_size
from chaeksas.contracts.extension import validate as validate_extension
from chaeksas.contracts.hashing import (
    FloatInPayloadError,
    canonical_json,
    content_hash_dir,
    content_hash_from_files,
    content_hash_zip,
    sha256_hex,
)
from chaeksas.contracts.manifest import (
    Built,
    ExtensionNeed,
    HumanNeeds,
    Manifest,
    Provides,
    Requires,
    ResourceRef,
    ServiceAppNeed,
    TaskTypeNeed,
    ToolpackRef,
    Trigger,
    validate,
)
from chaeksas.contracts.replay import (
    REPLAY_DEFAULT,
    REPLAY_MODES,
    ReplayMemory,
    ReplaySpec,
    ReplayStep,
)
from chaeksas.contracts.resources import (
    ContributedResource,
    ExtensionResource,
    InstalledOn,
    MissingResource,
    ResourceIndex,
    ResourceList,
    RuntimeHost,
    RuntimeResource,
    ServiceAppResource,
    ToolpackResource,
    blocking_at_deploy,
    missing,
)
from chaeksas.contracts.service_app import (
    AdminKeyCreated,
    AdminKeyCreateRequest,
    AdminKeyInfo,
    AdminStatus,
    Caller,
    CenterRegistration,
    Dependency,
    ExtensionRef,
    HealthResponse,
    KeySelfResponse,
    Operation,
    OperationStatus,
    OpRequest,
    OpResponse,
    ServiceAppKey,
    ServiceAppManifest,
    Usage,
    UsagePage,
    UsageRecord,
    admin_key_info,
    authorize,
    idempotency_key,
    resolve_mode,
)
from chaeksas.contracts.service_app import key_state as service_app_key_state
from chaeksas.contracts.service_app import prefix_of as service_app_prefix_of
from chaeksas.contracts.signing import (
    AdminKey,
    AdminKeyClaim,
    DeploymentClaim,
    DeploymentTarget,
    Envelope,
    ExtensionClaim,
    PackageClaim,
    RevokeClaim,
    key_id_for,
    parse_claim,
    sign,
    verify,
    verify_admin_key_addition,
    verify_package,
    verify_target,
    verify_time,
)

__all__ = [
    # 바탕
    "ContractModel",
    "SEVERITY_ERROR",
    "SEVERITY_WARNING",
    "SchemaVersioned",
    "Sha256",
    "Timestamp",
    # C1
    "Built",
    "ExtensionNeed",
    "HumanNeeds",
    "Manifest",
    "Provides",
    "Requires",
    "ResourceRef",
    "ServiceAppNeed",
    "TaskTypeNeed",
    "ToolpackRef",
    "Trigger",
    "Violation",
    "validate",
    # C2
    "AdminKey",
    "AdminKeyClaim",
    "DeploymentClaim",
    "DeploymentTarget",
    "Envelope",
    "ExtensionClaim",
    "FloatInPayloadError",
    "PackageClaim",
    "RevokeClaim",
    "canonical_json",
    "content_hash_dir",
    "content_hash_from_files",
    "content_hash_zip",
    "key_id_for",
    "parse_claim",
    "sha256_hex",
    "sign",
    "verify",
    "verify_admin_key_addition",
    "verify_package",
    "verify_target",
    "verify_time",
    # C3
    "EventBatchResponse",
    "RejectedLine",
    "RunEvent",
    "RunEventsResponse",
    "RunInfo",
    "RunListing",
    "missing_data_keys",
    # C4 (`AdminKey`는 C2가 소유한다)
    "ApprovalAck",
    "ApprovalDispatch",
    "CurrentRun",
    "DeploymentResult",
    "ExtensionState",
    "HeartbeatRequest",
    "HeartbeatResponse",
    "JobAck",
    "JobDispatch",
    "Queue",
    "QueueItem",
    "Readiness",
    "RegisterRequest",
    "RegisterResponse",
    "Runtimes",
    "Versions",
    "WorkerState",
    # C5
    "BotUiInfo",
    "BotUiKey",
    "DeploymentInfo",
    "ErrorBody",
    "JobCreateRequest",
    "JobInfo",
    "JobTarget",
    "ListParams",
    "PackageInfo",  # `MissingResource`는 C7이 소유한다
    "PreflightSummary",
    "cancel_outcome",
    "validate_deployment",
    "validate_job_create",
    # C6
    "AnswerRequest",
    "ApprovalCreateRequest",
    "ApprovalHost",
    "ApprovalInfo",
    "Form",
    "FormField",
    "apply_defaults",
    "request_id_for",
    "validate_answer",
    "validate_approval_create",
    # C7
    "BoundTo",
    "CenterKeyCreateRequest",
    "CenterKeyCreated",
    "CenterKeyInfo",
    "ContributedResource",
    "ExtensionResource",
    "InstalledOn",
    "MissingResource",  # `Operation`은 C11이 소유한다
    "ResourceIndex",
    "ResourceList",
    "RuntimeHost",
    "RuntimeResource",
    "ServiceAppResource",
    "ToolpackResource",
    "blocking_at_deploy",
    "center_key_prefix_of",
    "center_key_state",
    "expires_soon",
    "missing",
    "validate_center_key_create",
    # C11
    "AdminKeyCreateRequest",
    "AdminKeyCreated",
    "AdminKeyInfo",
    "AdminStatus",
    "Caller",
    "CenterRegistration",
    "Dependency",
    "OperationStatus",
    "UsagePage",
    "admin_key_info",
    "ExtensionRef",
    "HealthResponse",
    "KeySelfResponse",
    "OpRequest",
    "OpResponse",
    "Operation",
    "ServiceAppKey",
    "ServiceAppManifest",
    "Usage",
    "UsageRecord",
    "authorize",
    "idempotency_key",
    "resolve_mode",
    "service_app_key_state",
    "service_app_prefix_of",
    # C13 (`ExtensionClaim`은 C2가 소유한다)
    "AdapterAuth",
    "AdapterHealth",
    "AdapterLimits",
    "AdapterOperation",
    "AdapterRequest",
    "AdapterResponse",
    "Catalog",
    "CatalogItem",
    "ConfigurationItem",
    "ConsolePage",
    "Contributes",
    "Editor",
    "ErrorWhen",
    "Executor",
    "ExtensionManifest",
    "HttpAdapter",
    "KeyNeed",
    "LocalRuntime",
    "PreflightContribution",
    "ResourceContribution",
    "ResourceView",
    "Service",
    "StudioEditorContribution",
    "TaskTypeContribution",
    "Utility",
    "check_extension_api",
    "check_extension_size",
    "definition_hash",
    "task_type_conflicts",
    "validate_extension",
    "verify_external",
    # C14 (`ExtensionNeed`는 C1이, `FormField`는 C6이 소유한다)
    "AiTask",
    "Approval",
    "BUILTIN_VARS",
    "BpmnFlow",
    "BpmnNode",
    "BpmnProcess",
    "BpmnReadError",
    "Call",
    "Case",
    "CaseFile",
    "CaseMessage",
    "DataOutput",
    "Decision",
    "DecisionInput",
    "DecisionIo",
    "DecisionOutput",
    "DecisionRule",
    "Defaults",
    "DmnError",
    "DmnReadError",
    "Email",
    "ExtensionTask",
    "FileList",
    "InputDecl",
    "Loop",
    "ProcessInfo",
    "REPLAY_DEFAULT",
    "REPLAY_MODES",
    "Receive",
    "ReplayMemory",
    "ReplaySpec",
    "ReplayStep",
    "Rule",
    "ServiceCall",
    "Webhook",
    "available_vars",
    "blocking",
    "decision_io",
    "duration_hours",
    "expression_vars",
    "is_var_name",
    "matches_expected",
    "read_decisions",
    "read_process",
    "validate_bpmn",
]
