"""재무·회계 예제 (BX-01 ~ BX-08)."""

from exdsl import *  # noqa: F401,F403

EXAMPLES = []

# ───────────────────────────── BX-01 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-01", file="bx01_invoice_reconciliation", name="월별 청구서 대사", dept="재무·회계",
    origin="프로토타입 업무 A (실제로 만들어 돌림)", 
    run_location="server", trigger="타이머 — 매월 1일 09:00 (`0 9 1 * *`), 또는 작업 지시(대상월 지정)",
    background="""
공급사가 보낸 청구서 PDF(양식 3가지, 7건)를 발주 대장(xlsx)과 맞춰 본다. 문제없는 건은 지급 대상으로, 문제 있는 건은 보류로 나누고 대사표를 만든다. 보류가 있으면 담당자가 확인한 뒤 결과를 재무팀에 메일로 보낸다.

보류 규칙(6가지): 미등록 발주, 중복 청구, 금액 불일치, 부가세 ≠ 공급가의 10%, 미입고, 그리고 참고용으로 미청구 발주를 따로 적는다.
""",
    why_location="""
화면 조작이 없다 (문서 읽기 + 판단 + 메일). 결재가 며칠 늦어도 서버가 상태를 저장하고 기다리므로 PC를 붙잡지 않는다 (ADR-0016).
""",
    inputs=[("대상월", "string", False, "`YYYY-MM`. 비우면 지난달"),
            ("청구서폴더", "string", False, "청구서 PDF가 있는 공유 폴더 (서버에서 읽을 수 있는 경로)"),
            ("재무팀메일", "string", False, "받는 사람", "finance@example.com")],
    nodes=[
        start("Start", "매월 1일", kind="timer", cycle="0 9 1 * *"),
        script("Task_Month", "대상월 정하기",
               "대상월 = 대상월 or 지난달()\n대장파일 = 청구서폴더 + '/' + 대상월 + '/ledger_' + 대상월 + '.xlsx'"),
        flist("Task_Collect", "청구서 모으기", "{청구서폴더}/{대상월}", "청구서파일", pattern="*.pdf", count_as="청구서수"),
        ai("Task_ReadLedger", "발주 대장 읽기",
           goal("`대장파일`은 이번 달 발주 대장(xlsx)이다. 한 줄이 발주 한 건이다.",
                "모든 줄을 읽어 발주번호·공급사·공급가액·입고여부를 목록으로 돌려준다. 빈 줄과 합계 줄은 뺀다.",
                "대사·지급 판단은 하지 않는다. 값이 비어 있으면 비운 채로 둔다.",
                "- `발주목록`: list of {발주번호(string), 공급사(string), 공급가액(int), 입고(bool)}"),
           "doc", {"발주목록": "list"}, tools=["excel_parser_tool"]),
        ai("Task_ReadInvoice", "청구서 판독",
           goal("`청구서`는 PDF 한 장의 경로다. 공급사마다 양식이 다르다 (공급가액/과세 공급가, 발주번호/PO No./참조 발주).",
                "이 한 장에서 공급사·청구번호·발주번호·공급가액·부가세·합계를 읽는다.",
                "다른 청구서와 비교하거나 중복 여부를 판단하지 않는다 (그건 대사 단계의 일).",
                "- `청구`: {공급사, 청구번호, 발주번호(string — 숫자로 바꾸지 않는다), 공급가액(int), 부가세(int), 합계(int)}"),
           "doc", {"청구": "dict"}, tools=["pdf_text_tool"],
           loop=dict(collection="청구서파일", item="청구서", result="청구", collect_into="청구목록")),
        # 대사 규칙 6가지를 **그대로 적는다** — 판단은 사람이 읽고 감사할 수 있어야 한다 (AI가 아니라).
        script("Task_Reconcile", "대사",
               "발주 = 표를사전(발주목록, '발주번호')\n"
               "청구번호 = 열뽑기(청구목록, '발주번호')\n"
               "중복 = [n for n in 청구번호 if len([x for x in 청구번호 if x == n]) > 1]\n"
               "판정 = [dict(청구=c, 사유=("
               "'미등록 발주' if c['발주번호'] not in 발주 else "
               "('중복 청구' if c['발주번호'] in 중복 else "
               "('금액 불일치' if c['공급가액'] != 발주[c['발주번호']]['공급가액'] else "
               "('부가세 오류' if c['부가세'] != round(c['공급가액'] * 0.1) else "
               "('미입고' if not 발주[c['발주번호']]['입고'] else '')))))) for c in 청구목록]\n"
               "보류 = [x for x in 판정 if x['사유'] != '']\n"
               "지급대상 = [x['청구'] for x in 판정 if x['사유'] == '']\n"
               "미청구 = [o for o in 발주목록 if o['발주번호'] not in 청구번호]\n"
               "지급합계 = 합계(지급대상, '합계')\n보류건수 = len(보류)\n지급진행 = '지급 대상대로 진행'\n의견 = ''"),
        xgw("Gw_HasHold", "보류 있음?"),
        appr("Approve_Hold", "보류 건 확인", "청구서 보류 확인",
             ["대상월", "보류", "지급대상", "지급합계"],
             [fld("지급진행", "처리", "choice", True, ["지급 대상대로 진행", "이번 달 전체 보류"]), fld("의견", "의견")],
             location="center", description="보류 사유를 확인하세요. 승인하면 지급 대상만 지급 요청합니다."),
        script("Task_Report", "보고서 만들기",
               "지급대상 = [] if 지급진행 == '이번 달 전체 보류' else 지급대상\n지급합계 = 합계(지급대상, '합계')"),
        mail("Task_Mail", "재무팀에 보내기", ["{재무팀메일}"], "[{대상월}] 청구서 대사 결과 — 지급 {지급합계}원, 보류 {보류건수}건",
             "첨부한 대사표를 확인해 주세요.", attachments=["대사표경로"], store_as="발송결과"),
        script("Task_MailFailed", "메일 실패 기록", "발송오류 = error_message"),
        end("End", "끝"),
    ],
    flows=[f("Start", "Task_Month"), f("Task_Month", "Task_Collect"), f("Task_Collect", "Task_ReadLedger"), f("Task_ReadLedger", "Task_ReadInvoice"),
           f("Task_ReadInvoice", "Task_Reconcile"), f("Task_Reconcile", "Gw_HasHold"),
           f("Gw_HasHold", "Approve_Hold", "보류건수 > 0", "있음"), f("Gw_HasHold", "Task_Report", default=True, name="없음"),
           f("Approve_Hold", "Task_Report"), f("Task_Report", "Task_Mail"), f("Task_Mail", "End"),
           f("Bnd_MailFail", "Task_MailFailed"), f("Task_MailFailed", "End")],
    boundaries=[bnd("Bnd_MailFail", "Task_Mail", "error", "보내기 실패", error="SEND_FAILED")],
    data=[out("Data_Table", "대사표", "Task_Report", "대사표/대사표_{대상월}.md", "md",
              template="# 청구서 대사 — {대상월}\n\n- 지급 합계: {지급합계}원\n- 지급 대상: {지급대상}\n"
                       "- 보류 {보류건수}건: {보류}\n- 미청구 발주: {미청구}\n- 의견: {의견}\n",
              store_as="대사표경로")],
    variables=[("발주목록", "list", "Task_ReadLedger", "발주 대장의 줄"), ("청구목록", "list", "Task_ReadInvoice (반복)", "청구서 판독 결과"),
               ("지급대상", "list", "Task_Reconcile", "문제없는 청구"), ("보류", "list", "Task_Reconcile", "{청구, 사유}"),
               ("지급합계", "int", "Task_Reconcile", "원")],
    defaults={"limits": {"timeout_s": 180, "max_steps": 10}, "forbidden_actions": ["파일을 수정·삭제하지 않는다"]},
    cases=[
        Case("8월 정상", {"대상월": "2026-08", "청구서폴더": "samples/invoice_reconciliation"},
             {"지급합계": 6358000, "보류건수": 5}, {"Approve_Hold": {"지급진행": "지급 대상대로 진행", "의견": "보류 5건 공급사에 확인 요청"}},
             "샘플 7건: 지급 2건, 보류 5건(금액 불일치·미입고·미등록 발주·중복·부가세), 미청구 2건"),
        Case("8월 정상 (사람이 확인)", {"대상월": "2026-08", "청구서폴더": "samples/invoice_reconciliation"},
             {"보류건수": 5}, manual=True, description="결재 폼이 실제로 보이는지 확인"),
        Case("문제 없는 달", {"대상월": "2026-07", "청구서폴더": "samples/invoice_reconciliation"}, {"보류건수": 0},
             description="보류가 없으면 결재 없이 바로 보고"),
        Case("청구서 없음", {"대상월": "2026-06", "청구서폴더": "samples/invoice_reconciliation"}, {"지급합계": 0, "보류건수": 0},
             description="빈 폴더 — 반복이 0번 돌고 끝나야 한다"),
    ],
    features=["순차 반복 AI 태스크(`collect_into`)", "AI 문서 읽기(doc) + 규칙은 스크립트로", "조건부 결재(Center 결재함)",
              "파일 출력 → 메일 첨부(`store_as`)", "오류 경계 `SEND_FAILED`", "타이머 시작(월 1회)"],
    lessons=["목표를 템플릿 문구 그대로 두면 모델이 대장을 지어냈다 — 목표에 데이터가 어디 있는지 적는다.",
             "비어 있는 업무 파라미터가 실제 변수를 덮어썼다 — 경로처럼 실행마다 바뀌는 값은 파라미터가 아니라 입력으로.",
             "`발주번호`를 int로 두면 `PO-2608-001`이 `2608001`이 된다 — 번호는 string (C14 B8).",
             "판독 태스크가 중복을 먼저 판단해 버렸다 — 목표에 「판단하지 않는 것」을 적는다.",
             "결재 `show`를 문자열 하나로 쓰면 아무것도 안 보였다 — 배열로 (C14 B2).",
             "케이스가 하나뿐이었다 — 「문제 없는 달」·「청구서 없음」을 처음부터 둔다."],
    samples="프로토타입 `samples/invoice_reconciliation/2026-08/` — 청구서 PDF 7장(양식 3종), `ledger_2026-08.xlsx` 7줄. 심어 둔 문제: 금액 +90,000(유니스오피스), 미입고(삼정), 미등록 PO-2608-011(네오소재), 중복(대성테크 재발행), 부가세 180,000(코리아플러스), 미청구 발주 005·007. 새 저장소로 옮길 때 `samples/`에 복사한다.",
    service_keys={}, extensions=[],
))

# ───────────────────────────── BX-02 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-02", file="bx02_morning_fx_report", name="매일 아침 환율 점검 보고", dept="재무·회계",
    origin="프로토타입 업무 B (실제로 만들어 돌림)", 
    run_location="server", trigger="타이머 — 평일 09:00 (`0 9 * * 1-5`)",
    background="""
평일 아침마다 외부 환율 API에서 USD 기준 KRW·EUR·JPY 환율을 받아 통화별 상한·하한과 비교한다. 경고가 있을 때만 담당자에게 확인을 받고, 보고서를 만들어 메일로 보낸다. 메일이 실패해도 실행 전체가 실패하지 않게 오류 경계로 기록만 남긴다.
""",
    why_location="외부 API와 메일뿐이다. 결재를 기다리는 동안 서버는 상태를 저장한다.",
    inputs=[("상한", "dict", False, "통화별 상한. 비우면 운영 기본값(스크립트)"), ("하한", "dict", False, "통화별 하한"),
            ("담당자", "string", False, "받는 사람 메일", "finance@example.com")],
    nodes=[
        start("Start", "평일 09:00", kind="timer", cycle="0 9 * * 1-5"),
        ai("Task_FetchFx", "환율 조회",
           goal("업무 파라미터 `조회주소`가 환율 API 주소다.", "그 주소를 GET으로 한 번 불러 KRW·EUR·JPY 환율과 기준일을 꺼낸다.",
                "환율이 높은지 낮은지 판단하지 않는다.", "- `환율`: {KRW, EUR, JPY} (number)\n- `기준일`: string `YYYY-MM-DD`"),
           "api", {"환율": "dict", "기준일": "date"}, tools=["http_request_tool"],
           params={"조회주소": "https://api.frankfurter.dev/v1/latest?base=USD&symbols=KRW,EUR,JPY"}, limits={"max_steps": 6}),
        # `범위벗어남`은 **값 하나**를 본다 — 통화마다 돌린다 (인수 시험이 이 어긋남을 잡았다).
        script("Task_Check", "점검",
               "상한 = 상한 or {'KRW': 1400}\n하한 = 하한 or {'KRW': 1200}\n"
               "경고 = [{'통화': k, '값': 환율[k], '상한': 상한[k], '하한': 하한[k]} for k in 상한 "
               "if k in 환율 and 범위벗어남(환율[k], 하한[k], 상한[k])]\n경고수 = len(경고)"),
        xgw("Gw_Warn", "경고 있음?"),
        appr("Approve_Warn", "환율 경고 확인", "환율 경고 확인", ["기준일", "환율", "경고", "상한", "하한"],
             [fld("조치필요", "조치가 필요합니까?", "bool", True), fld("메모", "메모")], location="center"),
        script("Task_Report", "보고서 만들기",
               "조치 = ('필요' if 조치필요 else '불필요') if 경고수 > 0 else '해당 없음'"),
        mail("Task_Send", "담당자에게 보내기", ["{담당자}"], "[{기준일}] 환율 점검 — 경고 {경고수}건", "보고서를 첨부합니다.",
             attachments=["보고서경로"], store_as="발송결과"),
        script("Task_SendFailed", "메일 실패 기록", "발송오류 = error_message"),
        end("End"),
    ],
    flows=[f("Start", "Task_FetchFx"), f("Task_FetchFx", "Task_Check"), f("Task_Check", "Gw_Warn"),
           f("Gw_Warn", "Approve_Warn", "경고수 > 0", "있음"), f("Gw_Warn", "Task_Report", default=True, name="없음"),
           f("Approve_Warn", "Task_Report"), f("Task_Report", "Task_Send"), f("Task_Send", "End"),
           f("Bnd_SendFail", "Task_SendFailed"), f("Task_SendFailed", "End")],
    boundaries=[bnd("Bnd_SendFail", "Task_Send", "error", "보내기 실패", error="SEND_FAILED")],
    data=[out("Data_Report", "아침보고", "Task_Report", "아침보고/아침보고_{기준일}.md",
              template="# 아침 환율 점검 — {기준일}\n\n- 환율: {환율}\n- 경고 {경고수}건: {경고}\n- 조치: {조치}\n",
              store_as="보고서경로")],
    variables=[("환율", "dict", "Task_FetchFx", ""), ("경고", "list", "Task_Check", "{통화, 값, 기준, 방향}"),
               ("경고수", "int", "Task_Check", ""), ("보고서경로", "string", "Data_Report", "첨부 파일")],
    cases=[
        Case("평온한 아침", {"상한": {"KRW": 2000, "EUR": 1.2, "JPY": 200}, "하한": {"KRW": 500, "EUR": 0.5, "JPY": 100}}, {"경고수": 0}),
        Case("상한 돌파", {"상한": {"KRW": 1000, "EUR": 1.2, "JPY": 200}, "하한": {"KRW": 500, "EUR": 0.5, "JPY": 100}}, {"경고수": 1},
             {"Approve_Warn": {"조치필요": True, "메모": "환율 급등 — 결제 일정 확인 필요"}}),
        Case("상한 돌파 (사람이 확인)", {"상한": {"KRW": 1000}}, {"경고수": 1}, manual=True),
        Case("메일 서버 없음", {"상한": {"KRW": 2000}, "담당자": "nobody@invalid"}, {"경고수": 0}, description="메일이 실패해도 실행은 성공, `발송오류`가 채워짐"),
    ],
    features=["API AI 태스크 + 업무 파라미터(재생 때 `$param`)", "조건부 결재", "파일 출력 → 메일 첨부", "오류 경계로 메일 실패를 흡수", "평일 타이머"],
    lessons=["임계값은 처음에 숫자 하나였다가 통화별 dict로 바뀌었다 — 처음부터 dict로.",
             "운영 임계값은 스크립트 기본값에, 케이스는 입력으로만 덮어쓴다 (업무 파라미터는 케이스가 못 바꾼다).",
             "받는 사람 주소는 「설정에서 읽어 오기」가 아니라 **기본값 있는 입력**이다 (ADR-0025 — 식은 순수 함수만).",
             "보고서 모양은 스크립트가 글자를 이어 붙이지 않고 **파일 출력 템플릿**에 둔다 (같은 ADR).",
             "주소를 목표 문장에 쓰면 재생이 그 문장에 묶인다 — 업무 파라미터로.",
             "「성공했지만 결과가 틀린」 실수 4가지: 경로에 `outputs/` 두 번, 빈 템플릿, `store_as` 없음, 받는 사람 변수 없음 (C14 §파일 출력).",
             "작은 태스크는 재생해도 시간이 줄지 않았다 (LLM 7회→1회, 시간 같음) — 재생의 이득은 큰 태스크에서."],
    samples="외부 API `api.frankfurter.dev` (키 없음). 서버망에서 닿는지 먼저 확인한다.",
))

# ───────────────────────────── BX-03 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-03", file="bx03_expense_approval", name="지출 결재", dept="재무·회계",
    origin="프로토타입 업무 C (실제로 만들어 돌림)", 
    run_location="server", trigger="메시지 `expense_request` — 경비 시스템이 Center 메시지 API로 보냄 (C12)",
    background="""
경비 시스템에서 지출 신청이 오면 정책으로 먼저 거른다: 영수증이 없으면 바로 반려, 10만 원 이하면 자동 승인, 그 밖에는 결재자에게 보낸다. 결재는 며칠 걸릴 수 있다. 3일이 지나면 리마인드(결재는 계속 기다림), 7일이 지나면 기한 초과로 반려한다. 어떤 길로 끝나든 신청자에게 회신하고 처리 기록을 남긴다.
""",
    why_location="""
**결재를 며칠씩 기다리는 업무라 반드시 서버다.** PC Bot이면 결재를 기다리는 7일 동안 그 PC의 실행 자리를 쥐고 다른 Bot이 모두 대기열에 멈춘다 (ADR-0014). 서버는 기다리는 동안 상태를 저장하고 일꾼을 놓는다 (ADR-0015).
""",
    inputs=[("신청번호", "string", True, ""), ("신청자", "string", True, ""), ("항목", "string", True, ""),
            ("금액", "int", True, "원"), ("영수증", "bool", True, ""), ("회신주소", "string", True, "경비 시스템의 회신 웹훅"),
            ("자동승인한도", "int", False, "원", 100000), ("리마인드기한", "string", False, "ISO 기간", "P3D"), ("마감기한", "string", False, "ISO 기간", "P7D")],
    nodes=[
        start("Start", "지출 신청 도착", kind="message", message="expense_request"),
        script("Task_Precheck", "사전 점검",
               "기한초과 = False\n승인여부 = False\n결재의견 = ''\n경로 = '사전반려' if not 영수증 else ('자동승인' if 금액 <= 자동승인한도 else '결재')"),
        xgw("Gw_NeedApproval", "결재가 필요한가?"),
        appr("Approve_Expense", "결재 대기", "지출 결재", ["신청번호", "신청자", "항목", "금액", "영수증", "마감기한"],
             [fld("승인여부", "승인합니까?", "bool", True), fld("결재의견", "의견")], location="center",
             description="기한이 지나면 자동 반려됩니다."),
        hook("Task_Remind", "리마인드", "{회신주소}", body="fields:[신청번호, 리마인드기한]", store_as="리마인드발송"),
        end("End_Remind", "리마인드 끝"),
        script("Task_Expired", "기한 초과", "기한초과 = True"),
        script("Task_Result", "결과 정리",
               "결과 = '사전반려' if 경로 == '사전반려' else ('자동승인' if 경로 == '자동승인' else ('기한초과반려' if 기한초과 else ('승인' if 승인여부 else '반려')))"),
        hook("Task_Reply", "신청자에게 회신", "{회신주소}", body="fields:[신청번호, 결과, 결재의견]", store_as="회신결과"),
        script("Task_ReplyFailed", "회신 실패 기록", "회신오류 = error_message"),
        end("End"),
    ],
    flows=[f("Start", "Task_Precheck"), f("Task_Precheck", "Gw_NeedApproval"),
           f("Gw_NeedApproval", "Approve_Expense", "경로 == '결재'", "결재"), f("Gw_NeedApproval", "Task_Result", default=True, name="사전반려·자동승인"),
           f("Approve_Expense", "Task_Result"), f("Bnd_Remind", "Task_Remind"), f("Task_Remind", "End_Remind"),
           f("Bnd_Deadline", "Task_Expired"), f("Task_Expired", "Task_Result"),
           f("Task_Result", "Task_Reply"), f("Task_Reply", "End"), f("Bnd_ReplyFail", "Task_ReplyFailed"), f("Task_ReplyFailed", "End")],
    boundaries=[bnd("Bnd_Remind", "Approve_Expense", "timer", "리마인드 기한", interrupting=False, duration="리마인드기한"),
                bnd("Bnd_Deadline", "Approve_Expense", "timer", "마감 기한", duration="마감기한"),
                bnd("Bnd_ReplyFail", "Task_Reply", "error", "회신 실패", error="SEND_FAILED")],
    data=[out("Data_Log", "처리 기록", "Task_Result", "지출결재/{신청번호}.md",
              template="# 지출 결재 {신청번호}\n\n- 결과: {결과}\n- 의견: {결재의견}\n", store_as="기록경로")],
    variables=[("경로", "string", "Task_Precheck", "사전반려/자동승인/결재"), ("기한초과", "bool", "Task_Expired", ""),
               ("결과", "string", "Task_Result", "사전반려/자동승인/승인/반려/기한초과반려")],
    cases=[
        Case("영수증 없음", {"신청번호": "EX-2609-014", "신청자": "김하나", "항목": "택시", "금액": 25000, "영수증": False, "회신주소": {"$test_receiver": "reply"}}, {"결과": "사전반려"}),
        Case("소액 자동승인", {"신청번호": "EX-2609-014", "신청자": "김하나", "항목": "택시", "금액": 30000, "영수증": True, "회신주소": {"$test_receiver": "reply"}}, {"결과": "자동승인"}),
        Case("결재 승인", {"신청번호": "EX-2609-014", "신청자": "김하나", "항목": "출장 숙박", "금액": 480000, "영수증": True, "회신주소": {"$test_receiver": "reply"}, "리마인드기한": "PT30S", "마감기한": "PT60S"},
             {"결과": "승인"}, {"Approve_Expense": {"승인여부": True, "결재의견": "출장 확인함"}}),
        Case("기한 초과", {"신청번호": "EX-2609-015", "신청자": "김하나", "항목": "출장 숙박", "금액": 480000, "영수증": True, "회신주소": {"$test_receiver": "reply"}, "리마인드기한": "PT1S", "마감기한": "PT3S"},
             {"결과": "기한초과반려"}, description="자동 응답이 없으므로 타이머가 이긴다"),
    ],
    features=["메시지 시작(외부 시스템 → Center)", "비중단 타이머 경계(리마인드) + 중단 타이머 경계(마감)", "타이머 기간을 변수로",
              "네 갈래가 한 곳으로 합류", "서버의 긴 대기(상태 저장·재개)", "웹훅 회신 + 오류 경계"],
    lessons=["상태 저장·재개(며칠 대기)가 이 업무의 핵심이었다 — 서버 실행기가 맡는다 (C12 `run_waiting`/`run_resumed`).",
             "리마인드 Send Task가 결재가 끝날 때까지 늦게 실행된 결함이 있었다 (A-11) — 비중단 경계의 가지는 즉시 돌아야 한다.",
             "경계 타이머는 반복(`timeCycle`)을 지원하지 않아 리마인드는 한 번뿐이다 (C14).",
             "마감에 진 결재가 빨간색(실패)으로 보였다 — 정상 경로다. 「취소됨」(neutral)으로 표시한다.",
             "기한 값은 기본값 있는 입력으로 — 업무 파라미터면 케이스가 짧은 기한으로 바꿀 수 없다.",
             "결과 정리 스크립트는 네 갈래 어디서 와도 같은 변수를 읽는다. 결재 칸(`승인여부`·`결재의견`)과 `기한초과`는 결재를 거치지 않는 길에서는 생기지 않으므로 사전 점검에서 먼저 정해 둔다 (B11)."],
))

# ───────────────────────────── BX-04 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-04", file="bx04_tax_invoice_issue", name="세금계산서 발행 (포털 → 회계 프로그램)", dept="재무·회계",
    origin="프로토타입 시나리오 3 (실제로 만들어 돌림)", 
    run_location="pc", trigger="타이머 — 매월 1일 09:00, 또는 PC Bot 수동 실행",
    background="""
공급사 웹 포털에서 지난달 거래 내역 표를 읽어, 사내 회계 프로그램(데스크톱)의 발행대장에 한 줄씩 입력하고 저장한다. 시트 합계와 포털 합계가 같은지 검증한 뒤 발행 보고서를 남기고 담당자에게 알린다.
""",
    why_location="""
웹 포털 화면과 데스크톱 회계 프로그램을 조작해야 한다 → **PC**. 실행 위치를 서버로 두면 Studio 「실행 전 검사」가 UI 태스크를 오류로 막는다 (C14 B6).
""",
    inputs=[("대상월", "string", False, "`YYYY-MM`, 비우면 지난달"), ("최소발행금액", "int", False, "합계가 이보다 작으면 발행하지 않음"),
            ("담당자메일", "string", False, "", "tax@example.com")],
    nodes=[
        start("Start", "매월 1일", kind="timer", cycle="0 9 1 * *"),
        script("Task_Prepare", "발행 준비", "대상월 = 대상월 or 지난달()\n최소발행금액 = 최소발행금액 or 0"),
        ui("Task_ReadPortal", "거래 내역 조회", "supplier.portal.transactions",
           [dict(key="filter.month", action="fill", value="{대상월}"), dict(key="filter.search", action="click"),
            dict(key="result.table", action="read_table", result="거래내역")]),
        script("Task_Sum", "합계 검산", "건수 = len(거래내역)\n포털합계 = 합계(거래내역, '금액')\n발행대상 = 건수 > 0 and 포털합계 >= 최소발행금액"),
        xgw("Gw_Issue", "발행 대상?"),
        ui("Task_EnterBook", "회계 프로그램 입력", "accounting.taxbook.sheet",
           [dict(key="row.next", action="fill", value="{행}"), dict(key="menu.save", action="click")],
           loop=dict(collection="거래내역", item="행", result="입력결과", collect_into="입력결과목록")),
        ui("Task_ReadTotal", "시트 합계 읽기", "accounting.taxbook.sheet", [dict(key="cell.total", action="read", result="시트합계")]),
        script("Task_Verify", "발행 검증", "검증통과 = 시트합계 == 포털합계\n검증메모 = '' if 검증통과 else '합계가 다름'"),
        mail("Task_Notify", "담당자 통지", ["{담당자메일}"], "[{대상월}] 세금계산서 발행 {건수}건 — 검증 {검증통과}", "보고서를 첨부합니다.",
             attachments=["보고서경로"], store_as="통지결과"),
        end("End_Skip", "발행 안 함"),
        end("End"),
    ],
    flows=[f("Start", "Task_Prepare"), f("Task_Prepare", "Task_ReadPortal"), f("Task_ReadPortal", "Task_Sum"), f("Task_Sum", "Gw_Issue"),
           f("Gw_Issue", "Task_EnterBook", "발행대상", "발행"), f("Gw_Issue", "End_Skip", default=True, name="대상 없음"),
           f("Task_EnterBook", "Task_ReadTotal"), f("Task_ReadTotal", "Task_Verify"), f("Task_Verify", "Task_Notify"), f("Task_Notify", "End")],
    data=[out("Data_Report", "발행 보고", "Task_Verify", "세금계산서/{대상월}_발행보고.md",
              template="# 세금계산서 발행 보고 — {대상월}\n\n- 건수: {건수}\n- 포털 합계: {포털합계}\n"
                       "- 회계 시트 합계: {시트합계}\n- 검증: {검증통과} {검증메모}\n",
              store_as="보고서경로")],
    service_keys={"ui-automation": "finance-tax"}, extensions=[{"id": "ui-automation", "version": ">=0.4,<0.5"}],
    defaults={"forbidden_actions": ["포털에서 수정·삭제 링크를 누르지 않는다", "발행대장의 머리글과 합계 수식 칸을 고치지 않는다"],
              "confirm_triggers": ["포털 로그인 화면이 나타남"], "web": {"profile": "supplier-portal"}},
    variables=[("거래내역", "list", "Task_ReadPortal", "표의 줄"), ("포털합계", "int", "Task_Sum", ""), ("시트합계", "int", "Task_ReadTotal", ""),
               ("검증통과", "bool", "Task_Verify", "")],
    cases=[
        Case("정상 발행", {"대상월": "2026-08"}, {"건수": 4, "검증통과": True}),
        Case("발행 대상 없음", {"대상월": "2026-08", "최소발행금액": 1000000}, {"발행대상": False}),
        Case("로그인 만료", {"대상월": "2026-08"}, {}, manual=True, description="포털 세션이 만료되면 확인 창(CMN-01)으로 사람이 로그인한 뒤 계속"),
    ],
    features=["PC Bot + UI 태스크(웹 읽기·데스크톱 입력)", "UI 태스크 반복", "프로세스 기본값(금지 행동·확인 트리거)",
              "확인(confirmation) — 로그인 화면", "실행 위치 PC의 정당한 사례 (서버 우선의 예외)"],
    lessons=["프로토타입은 이 업무를 HYBRID AI 태스크 하나로 했다 (자율 388초, 재생 56초). 새 구조에서는 등록된 화면이면 UI 태스크(셀렉터 사다리)로 — LLM 없이 기계적 속도.",
             "합성 키 입력(Ctrl+S)이 조용히 무시됐다 (Wayland) — 저장은 메뉴 요소(`menu.save`)로 등록한다. Windows에서는 S1 스파이크로 확인.",
             "`.xlsx`로 저장하면 경고 창이 무인 실행을 막았다 — 데스크톱 앱의 모달은 확인 트리거로 등록한다.",
             "셀 읽기가 수식을 돌려줬다 — `read`는 계산된 값을 읽도록 요소를 등록한다.",
             "남은 프로세스가 다음 실행을 가로챘다 — UI 태스크 「실행 후 닫기」를 켠다.",
             "시작 주소를 케이스마다 바꿀 수 없었다 — 시작 주소는 화면 등록(C9)의 기본 주소, 케이스는 필터 값만 바꾼다."],
    samples="프로토타입은 the-internet.herokuapp.com/tables(4줄, 합계 251)와 `taxbook.ods`를 썼다. 새 구조에서는 사내 시험 포털 화면을 BUI-06으로 등록해 쓴다.",
))

# ───────────────────────────── BX-05 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-05", file="bx05_month_end_close", name="월말 마감 체크리스트", dept="재무·회계",
    origin="프로토타입 시나리오 9 (제안만 됨) → 새로 설계",
    run_location="server", trigger="타이머 — 매월 말일 18:00 (`0 18 L * *`)",
    background="""
월말 마감은 여러 부서의 완료 통보를 기다린다: 매출 확정(영업), 매입 확정(구매), 재고 실사(물류). 세 통보가 모두 오면 결산 분개를 만들고 재무팀장 결재 후 마감한다. 매출 통보가 하루를 넘기면 영업에 독촉한다. 진행 단계마다 이정표를 남겨 콘솔에서 어디까지 왔는지 보이게 한다. 팀장이 마감을 보류하면 재무팀에 알리고 끝낸다 (다음 조치는 사람이 새 실행으로).
""",
    why_location="여러 날 기다리는 메시지 3개가 핵심이다 → 서버. 각 부서 시스템은 Center 메시지 API로 완료를 알린다.",
    inputs=[("마감월", "string", False, "`YYYY-MM`. 비우면 이번 달"), ("영업담당", "string", False, "독촉 받는 사람", "sales@example.com"),
            ("재무팀메일", "string", False, "", "finance@example.com")],
    nodes=[
        start("Start", "말일 18:00", kind="timer", cycle="0 18 L * *"),
        script("Task_Init", "마감월 정하기", "마감월 = 마감월 or 이번달()"),
        throw("Ms_Open", "마감 시작"),
        pgw("Gw_Split", "세 부서 기다리기"),
        recv("Recv_Sales", "매출 확정 받기", "close_sales_done", "마감월", payload=["매출확정"]),
        recv("Recv_Purchase", "매입 확정 받기", "close_purchase_done", "마감월", payload=["매입확정"]),
        recv("Recv_Stock", "재고 실사 받기", "close_stock_done", "마감월", payload=["재고실사"]),
        mail("Task_RemindSales", "영업 독촉", ["{영업담당}"], "[{마감월}] 매출 확정 통보를 기다립니다", "오늘 안에 확정해 주세요."),
        end("End_RemindSales", "독촉 끝"),
        pgw("Gw_Join", "모두 도착"),
        throw("Ms_AllIn", "통보 완료"),
        ai("Task_Journal", "결산 분개 초안",
           goal("`매출확정`, `매입확정`, `재고실사`는 각 부서가 보낸 확정 자료(JSON)다.",
                "계정과목표(업무 파라미터 `계정과목`)에 맞춰 결산 분개 초안을 만든다.",
                "금액을 고치거나 누락분을 추정하지 않는다. 맞지 않으면 `불일치`에 적는다.",
                "- `분개초안`: list of {계정, 차변, 대변, 적요}\n- `불일치`: list of string"),
           "llm", {"분개초안": "list", "불일치": "list"}, params={"계정과목": ["매출", "매출원가", "외상매출금", "외상매입금", "상품"]}),
        appr("Approve_Close", "마감 승인", "월말 마감 승인", ["마감월", "분개초안", "불일치"],
             [fld("승인", "마감합니까?", "bool", True), fld("메모", "메모")], location="center"),
        xgw("Gw_Close", "마감?"),
        throw("Ms_Closed", "마감 완료"),
        end("End"),
        mail("Task_Hold", "마감 보류 알림", ["{재무팀메일}"], "[{마감월}] 월말 마감 보류", "{메모}"),
        end("End_Hold", "보류"),
    ],
    flows=[f("Start", "Task_Init"), f("Task_Init", "Ms_Open"), f("Ms_Open", "Gw_Split"),
           f("Gw_Split", "Recv_Sales"), f("Gw_Split", "Recv_Purchase"), f("Gw_Split", "Recv_Stock"),
           f("Recv_Sales", "Gw_Join"), f("Recv_Purchase", "Gw_Join"), f("Recv_Stock", "Gw_Join"),
           f("Bnd_SalesLate", "Task_RemindSales"), f("Task_RemindSales", "End_RemindSales"),
           f("Gw_Join", "Ms_AllIn"), f("Ms_AllIn", "Task_Journal"), f("Task_Journal", "Approve_Close"), f("Approve_Close", "Gw_Close"),
           f("Gw_Close", "Ms_Closed", "승인", "마감"), f("Gw_Close", "Task_Hold", default=True, name="보류"),
           f("Ms_Closed", "End"), f("Task_Hold", "End_Hold")],
    boundaries=[bnd("Bnd_SalesLate", "Recv_Sales", "timer", "하루 지남", interrupting=False, duration="P1D")],
    data=[out("Data_Journal", "결산 분개", "Approve_Close", "마감/{마감월}_분개.json", "json", variables=["분개초안", "불일치", "승인", "메모"], store_as="분개경로")],
    variables=[("매출확정", "dict", "Recv_Sales (메시지 본문)", ""), ("매입확정", "dict", "Recv_Purchase", ""), ("재고실사", "dict", "Recv_Stock", "")],
    cases=[Case("세 통보 모두 도착", {"마감월": "2026-09"}, {"승인": True, "분개경로": "*"}, {"Approve_Close": {"승인": True, "메모": "이상 없음"}},
                messages=[dict(after_s=2, name="close_sales_done", correlation="2026-09", payload={"매출확정": {"매출": 120000000}}),
                          dict(after_s=2, name="close_purchase_done", correlation="2026-09", payload={"매입확정": {"매입": 80000000}}),
                          dict(after_s=2, name="close_stock_done", correlation="2026-09", payload={"재고실사": {"상품": 30000000}})]),
           Case("팀장 보류", {"마감월": "2026-09"}, {"승인": False}, {"Approve_Close": {"승인": False, "메모": "매입 불일치 확인 후 재마감"}},
                messages=[dict(after_s=2, name="close_sales_done", correlation="2026-09", payload={"매출확정": {"매출": 120000000}}),
                          dict(after_s=2, name="close_purchase_done", correlation="2026-09", payload={"매입확정": {"매입": 80000000}}),
                          dict(after_s=2, name="close_stock_done", correlation="2026-09", payload={"재고실사": {"상품": 30000000}})])],
    features=["병렬 분기·합류", "받기 태스크 3개 + 상관 키(`마감월`)", "받기 태스크의 비중단 타이머(독촉)", "이정표(중간 던지기 이벤트)",
              "JSON 파일 출력", "케이스가 메시지를 보냄 (`messages`)", "타이머 시작 + 선택 입력 (비면 스크립트가 정함)"],
    lessons=["타이머로 시작하는 BPM 프로세스에 필수 입력을 두면 채울 사람이 없다 — 선택 입력으로 두고 첫 스크립트에서 정한다.",
             "독촉은 영업 가지에만 붙였다. 모든 가지에 붙이면 그림이 복잡해지므로 필요한 곳만.",
             "cron `L`(말일)은 엔진이 지원하는지 M3에서 확인하고, 안 되면 운영자가 일정으로 지정한다. 「마지막 영업일」은 cron으로 표현되지 않는다 — 필요하면 매일 돌고 첫 스크립트가 영업일 달력으로 걸러 끝낸다.",
             "메시지가 받기 태스크보다 먼저 오면 C12는 `no_receiver`로 거부한다. 부서 시스템이 마감 시작 전에 보내면 잃는다 — 메시지 보관(TTL)은 README 「아직 정하지 않은 것」."],
))

# ───────────────────────────── BX-06 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-06", file="bx06_bulk_credit_check", name="다건 거래처 신용 조회", dept="재무·회계",
    origin="프로토타입 시나리오 10 (제안만 됨) → 외부 확장으로 새로 설계", 
    run_location="server", trigger="작업 지시 — 거래처 목록(최대 50곳)을 입력으로",
    background="""
분기마다 주요 거래처 50곳의 신용등급을 외부 신용정보 서비스에서 조회한다. 결과를 규칙으로 「정상/주의/위험」 3단계로 나누고, 위험 거래처는 영업·재무에 알린다. 외부 신용정보 서비스는 우리 계약(C11)을 따르지 않는 외부 앱이므로 **외부 확장의 HTTP 어댑터**로 붙인다.
""",
    why_location="외부 API 50번 호출 — 서버에서 병렬 반복으로 빨리 끝낸다. PC에서는 병렬 반복도 차례로 돈다 (C14).",
    inputs=[("거래처목록", "list", True, "{사업자번호, 이름}"), ("영업팀메일", "string", False, "", "sales@example.com"), ("재무팀메일", "string", False, "", "finance@example.com")],
    nodes=[
        start("Start", "조회 요청"),
        svc("Task_Credit", "신용 조회", "ext-credit", "lookup", {"biz_no": "거래처.사업자번호"}, {"신용": "result"},
            loop=dict(collection="거래처목록", item="거래처", result="신용", collect_into="신용목록", parallel=True), retry={"max": 2, "on": [429, 503]}),
        rule("Task_Grade", "등급 나누기", "credit_grade", {"score": "신용.score", "overdue": "신용.overdue"}, {"등급": "grade"},
             loop=dict(collection="신용목록", item="신용", result="등급", collect_into="등급목록")),
        script("Task_Pick", "위험 거래처 추리기", "결과표 = [dict(거래처, 등급=g) for 거래처, g in zip(거래처목록, 등급목록)]\n위험 = [x for x in 결과표 if x.등급 == '위험']\n위험수 = len(위험)"),
        xgw("Gw_Risk", "위험 있음?"),
        mail("Task_Alert", "위험 알림", ["{영업팀메일}", "{재무팀메일}"], "신용 위험 거래처 {위험수}곳", "첨부를 확인하세요.", attachments=["결과경로"]),
        end("End"),
    ],
    flows=[f("Start", "Task_Credit"), f("Task_Credit", "Task_Grade"), f("Task_Grade", "Task_Pick"), f("Task_Pick", "Gw_Risk"),
           f("Gw_Risk", "Task_Alert", "위험수 > 0", "있음"), f("Gw_Risk", "End", default=True, name="없음"), f("Task_Alert", "End")],
    data=[out("Data_Result", "신용 조회 결과", "Task_Pick", "신용/{오늘}_신용조회.xlsx", "xlsx", variables=["결과표"], sheet="결과", store_as="결과경로")],
    service_keys={"ext-credit": "finance-credit"}, extensions=[{"id": "ext-credit", "version": ">=1,<2"}],
    decisions=[Decision("credit_grade", "신용 등급 분류", [("신용점수", "score", "number"), ("연체", "overdue", "boolean")],
                        [("grade", "string")],
                        [(["-", "true"], ['"위험"'], "연체가 있으면 점수와 무관하게 위험"),
                         (["< 600", "-"], ['"위험"'], ""), (["[600..750)", "-"], ['"주의"'], ""), ([">= 750", "-"], ['"정상"'], "")])],
    cases=[Case("소량 3곳", {"거래처목록": [{"사업자번호": "123-45-67890", "이름": "가나상사"}, {"사업자번호": "234-56-78901", "이름": "다라물산"}, {"사업자번호": "345-67-89012", "이름": "마바테크"}]},
                {"위험수": 1}, description="시험용 외부 앱 모의 서버가 마바테크를 연체로 돌려준다")],
    features=["외부 확장(HTTP 어댑터)의 서비스 앱 태스크", "병렬 다중 인스턴스 (서버에서 동시)", "규칙 태스크 반복 (한 건씩 DMN)", "재시도 정책(429·503)", "xlsx 출력"],
    lessons=["프로토타입에 병렬 반복 예제가 하나도 없었다 — 이 예제가 메운다.",
             "외부 앱이 멱등을 보장하지 않으면 시간 초과 때 자동으로 다시 부르지 않는다 (C13 `idempotent:false`) — 조회는 멱등이므로 정의에 `idempotent: true`로 둔다.",
             "외부 확장 정의는 Admin 서명이 있어야 쓰인다 (C2 `extension`) — 시험 전에 서명 절차를 거친다.",
             "서버에 배포하려면 그 작업이 결정 수행을 지원해야 한다 (C1 R8). 외부 정의의 `modes` 기본값은 자율 수행뿐이므로 `lookup`에 결정 수행을 명시한다 (C13).",
             "DMN은 한 건을 판정한다. 목록을 통째로 넘기지 말고 규칙 태스크를 반복한다."],
    samples="시험용 외부 앱 모의 서버(`samples/mock-credit/`, M5에 만든다): 사업자번호 끝자리로 점수·연체를 정해 돌려준다.",
))

# ───────────────────────────── BX-07 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-07", file="bx07_corporate_card_review", name="법인카드 사용 내역 정리", dept="재무·회계",
    origin="새로 설계", 
    run_location="server", trigger="타이머 — 매주 월요일 08:30 (`30 8 * * 1`)",
    background="""
지난주 법인카드 사용 내역(카드사 CSV)을 읽어 건마다 계정과목을 붙이고, 사용 정책(주말·심야·업종 제한·1회 한도)을 규칙으로 점검한다. 정책 위반 건만 모아 사용자 소속 팀장에게 소명 확인을 받고, 결과를 회계 전표 업로드용 xlsx로 만든다.
""",
    why_location="파일·규칙·결재뿐이다. 팀장 결재를 기다리는 동안 서버가 상태를 저장한다.",
    inputs=[("내역파일", "string", False, "카드사 CSV 경로. 비우면 공유 폴더의 지난주 파일"), ("카드폴더", "string", False, "", "\\\\fileserver\\재무\\법인카드")],
    nodes=[
        start("Start", "매주 월요일", kind="timer", cycle="30 8 * * 1"),
        script("Task_File", "파일 정하기", "내역파일 = 내역파일 or 카드폴더 + '/' + 지난주표기() + '.csv'"),
        ai("Task_Parse", "내역 읽기",
           goal("`내역파일`은 카드사가 준 CSV다. 열 이름이 카드사마다 조금씩 다르다.",
                "모든 줄을 {승인번호, 일시, 요일(월~일), 시(0~23), 가맹점, 업종, 금액, 사용자}로 정리한다. 요일·시는 일시에서 계산한다.",
                "정책 위반 여부는 판단하지 않는다.", "- `내역`: list"),
           "doc", {"내역": "list"}, tools=["csv_parser_tool"]),
        ai("Task_Account", "계정과목 붙이기",
           goal("`건`은 카드 사용 한 건이다. 업무 파라미터 `계정과목표`에 업종별 기본 계정이 있다.",
                "이 건의 계정과목을 하나 고르고 근거를 한 줄로 적는다.",
                "금액을 바꾸지 않는다.", "- `분류`: {승인번호, 계정과목, 근거}"),
           "llm", {"분류": "dict"}, params={"계정과목표": {"음식점": "복리후생비", "택시": "여비교통비", "숙박": "여비교통비", "문구": "소모품비"}},
           loop=dict(collection="내역", item="건", result="분류", collect_into="분류목록")),
        rule("Task_Policy", "정책 점검", "card_policy", {"요일": "건.요일", "시": "건.시", "업종": "건.업종", "금액": "건.금액"}, {"사유": "violation"},
             loop=dict(collection="내역", item="건", result="사유", collect_into="사유목록")),
        script("Task_Collect", "위반 모으기", "위반 = [dict(건, 사유=s) for 건, s in zip(내역, 사유목록) if len(s) > 0]\n위반건수 = len(위반)\n인정 = None"),
        xgw("Gw_Violation", "위반 있음?"),
        appr("Approve_Explain", "팀장 소명 확인", "법인카드 정책 위반 소명", ["위반"],
             [fld("인정", "업무상 사용으로 인정합니까?", "bool", True), fld("사유", "사유", required=True)], location="center"),
        script("Task_Build", "전표 자료 만들기",
               "계정 = 표를사전(분류목록, '승인번호')\n"
               "위반번호 = 열뽑기(위반, '승인번호')\n"
               "전표 = [dict(건, 계정과목=계정[건['승인번호']]['계정과목'], "
               "소명=('인정' if 인정 else '미인정') if 건['승인번호'] in 위반번호 else '') for 건 in 내역]"),
        end("End"),
    ],
    flows=[f("Start", "Task_File"), f("Task_File", "Task_Parse"), f("Task_Parse", "Task_Account"), f("Task_Account", "Task_Policy"),
           f("Task_Policy", "Task_Collect"), f("Task_Collect", "Gw_Violation"),
           f("Gw_Violation", "Approve_Explain", "위반건수 > 0", "있음"), f("Gw_Violation", "Task_Build", default=True, name="없음"),
           f("Approve_Explain", "Task_Build"), f("Task_Build", "End")],
    data=[out("Data_Upload", "전표 업로드 파일", "Task_Build", "카드/{오늘}_전표.xlsx", "xlsx", variables=["전표"], sheet="전표", store_as="전표경로")],
    decisions=[Decision("card_policy", "법인카드 사용 정책", [("요일", "요일", "string"), ("시각", "시", "number"), ("업종", "업종", "string"), ("금액", "금액", "number")],
                        [("violation", "string")],
                        [(['"토","일"', "-", "-", "-"], ['"주말 사용"'], ""), (["-", ">= 23", "-", "-"], ['"심야 사용"'], ""),
                         (["-", "-", '"유흥","골프"', "-"], ['"제한 업종"'], ""), (["-", "-", "-", "> 500000"], ['"1회 한도 초과"'], "")], hit="COLLECT")],
    cases=[Case("위반 1건", {"내역파일": "samples/card/2026-09-W4.csv"}, {"위반건수": 1}, {"Approve_Explain": {"인정": True, "사유": "고객 접대 — 사전 보고됨"}}),
           Case("위반 없음", {"내역파일": "samples/card/2026-09-W3.csv"}, {"위반건수": 0})],
    features=["AI 분류 반복 + 규칙 점검 분리 (판단은 규칙, 분류는 AI)", "규칙 태스크 반복 + DMN `COLLECT` (한 건에 위반 여러 개, 없으면 빈 목록)", "조건부 결재", "xlsx 출력"],
    lessons=["분류(AI)와 정책 판단(규칙)을 한 목표에 넣지 않는다 — 판단이 재생·감사 가능해야 한다.",
             "업무 파라미터(계정과목표)는 운영 값, 케이스는 파일만 바꾼다.",
             "`COLLECT` 표에 「위반 없음 → null」 같은 잡이 줄을 두면 모든 건이 결과 하나를 갖게 되어 「위반 있음」이 항상 참이 된다. 맞는 줄이 없으면 빈 목록이 되게 둔다.",
             "DMN이 읽는 칸(요일·시)은 앞 태스크의 반환에 있어야 한다 — 판독 목표의 반환 칸을 DMN 입력에 맞춰 정한다."],
    samples="`samples/card/` — 카드사 CSV 2주치 (M3에 만든다, 가상의 사용자·가맹점).",
))

# ───────────────────────────── BX-08 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-08", file="bx08_receivable_dunning", name="매출채권 연체 독촉", dept="재무·회계",
    origin="새로 설계", 
    run_location="server", trigger="타이머 — 평일 10:00 (`0 10 * * 1-5`)",
    background="""
ERP에서 만기가 지난 매출채권을 가져와 거래처마다 연체 단계(1차 안내 / 2차 독촉 / 법무 이관 검토)를 규칙으로 정한다. 1·2차는 AI가 거래처별 독촉 메일 초안을 쓰고 보낸다. 법무 이관 검토 대상(연체 90일 이상 또는 1억 원 이상)은 재무팀장 결재를 받는다.
""",
    why_location="ERP 연동은 사내 확장(서비스 앱)의 API로, 메일·결재만 있다 → 서버.",
    nodes=[
        start("Start", "매일 10:00", kind="timer", cycle="0 10 * * 1-5"),
        svc("Task_Overdue", "연체 채권 조회", "erp", "list_overdue_receivables", {"기준일": "오늘"}, {"연체목록": "items"}),
        rule("Task_Stage", "단계 정하기", "dunning_stage", {"연체일수": "채권.연체일수", "금액": "채권.금액"}, {"단계": "단계"},
             loop=dict(collection="연체목록", item="채권", result="단계", collect_into="단계목록")),
        script("Task_Split", "단계별 나누기", "채권단계 = [dict(c, 단계=s) for c, s in zip(연체목록, 단계목록)]\n안내대상 = [x for x in 채권단계 if x.단계 in ('1차', '2차')]\n이관대상 = [x for x in 채권단계 if x.단계 == '이관검토']\n이관건수 = len(이관대상)"),
        ai("Task_Draft", "독촉 메일 초안",
           goal("`대상`은 거래처 하나의 연체 정보다 (거래처명, 금액, 연체일수, 단계).",
                "단계에 맞는 정중한 독촉 메일 제목과 본문을 쓴다. 1차는 안내, 2차는 기한을 명시한 독촉.",
                "법적 조치를 언급하지 않는다. 금액·날짜를 바꾸지 않는다.", "- `메일`: {받는사람, 제목, 본문}"),
           "llm", {"메일": "dict"}, loop=dict(collection="안내대상", item="대상", result="메일", collect_into="메일목록")),
        svc("Task_SendBulk", "독촉 메일 발송", "erp", "send_customer_mail", {"메일": "메일목록"}, {"발송결과": "result"}),
        xgw("Gw_Escalate", "이관 검토 있음?"),
        appr("Approve_Legal", "법무 이관 결재", "연체 채권 법무 이관", ["이관대상"],
             [fld("이관", "법무로 넘깁니까?", "bool", True), fld("메모", "메모")], location="center"),
        xgw("Gw_Transfer", "이관?"),
        svc("Task_Transfer", "법무 이관 등록", "erp", "mark_legal_transfer", {"대상": "이관대상"}, {"등록결과": "result"}),
        end("End"),
    ],
    flows=[f("Start", "Task_Overdue"), f("Task_Overdue", "Task_Stage"), f("Task_Stage", "Task_Split"), f("Task_Split", "Task_Draft"),
           f("Task_Draft", "Task_SendBulk"), f("Task_SendBulk", "Gw_Escalate"),
           f("Gw_Escalate", "Approve_Legal", "len(이관대상) > 0", "있음"), f("Gw_Escalate", "End", default=True, name="없음"),
           f("Approve_Legal", "Gw_Transfer"), f("Gw_Transfer", "Task_Transfer", "이관", "이관"), f("Gw_Transfer", "End", default=True, name="보류"),
           f("Task_Transfer", "End")],
    service_keys={"erp": "finance-ar"}, extensions=[{"id": "erp", "version": ">=1,<2"}],
    decisions=[Decision("dunning_stage", "연체 단계", [("연체일수", "연체일수", "number"), ("금액", "금액", "number")], [("단계", "string")],
                        [([">= 90", "-"], ['"이관검토"'], ""), (["-", ">= 100000000"], ['"이관검토"'], ""),
                         (["[30..90)", "-"], ['"2차"'], ""), (["[1..30)", "-"], ['"1차"'], "")])],
    cases=[Case("평소", {}, {"이관건수": 0}, description="시험용 ERP 모의 서버: 연체 3건(10일·40일·20일)"),
           Case("이관 1건", {}, {"이관건수": 1}, {"Approve_Legal": {"이관": True}}, "모의 서버에 95일 연체 1건 추가")],
    features=["사내 확장(ERP 서비스 앱) 작업 호출", "DMN으로 단계 결정", "AI 메일 초안 반복", "결재 후 후속 API 등록"],
    lessons=["AI가 법적 표현을 쓰지 않게 「판단하지 않는 것」에 명시한다.",
             "메일 발송은 ERP의 고객 메일 기능(서비스 앱 작업)으로 — 발송 이력이 ERP에 남는다."],
))
