"""운영·법무·IT·고객 예제 (BX-30 ~ BX-37)."""

from exdsl import *  # noqa: F401,F403

EXAMPLES = []

# ───────────────────────────── BX-30 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-30", file="bx30_contract_review", name="계약서 검토", dept="운영·법무·IT·고객",
    origin="프로토타입 시나리오 4 (진행 중이던 것 — 호출 3개, 사전 점검까지)", 
    run_location="server", trigger="메시지 `contract_review` — 전자계약 시스템의 검토 요청",
    background="""
계약서 초안이 오면 조항을 뽑고, 위험도가 높은 세 가지 조항(손해배상·지식재산·해지)을 공유 BPM 프로세스 「조항 검토」(BX-37)로 각각 검토한다. 셋의 결과를 모아 위험 등급을 정하고, 높으면 법무팀 결재를 받는다. 검토 의견서를 만들어 요청 시스템에 돌려준다.
""",
    why_location="문서·AI·결재 — 서버.",
    inputs=[("요청번호", "string", True, ""), ("계약서", "string", True, "PDF 경로"), ("상대방", "string", True, ""), ("회신주소", "string", True, "")],
    nodes=[
        start("Start", "검토 요청", kind="message", message="contract_review"),
        ai("Task_Extract", "조항 뽑기",
           goal("`계약서`는 계약서 PDF다.", "손해배상, 지식재산, 해지 조항의 원문을 찾아 그대로 옮긴다. 조항 번호도 적는다.",
                "조항이 유리한지 불리한지 판단하지 않는다. 없으면 빈 문자열.",
                "- `손해배상조항`: string\n- `지재권조항`: string\n- `해지조항`: string"),
           "doc", {"손해배상조항": "string", "지재권조항": "string", "해지조항": "string"}, tools=["pdf_text_tool"]),
        pgw("Gw_Split", "세 조항 동시에"),
        call("Call_Damages", "손해배상 검토", "Proc_bx37_clause_review", {"조항": "손해배상조항", "종류": "'손해배상'"}, {"손해배상결과": "결과"}),
        call("Call_IP", "지재권 검토", "Proc_bx37_clause_review", {"조항": "지재권조항", "종류": "'지식재산'"}, {"지재권결과": "결과"}),
        call("Call_Term", "해지 검토", "Proc_bx37_clause_review", {"조항": "해지조항", "종류": "'해지'"}, {"해지결과": "결과"}),
        pgw("Gw_Join", "모으기"),
        script("Task_Grade", "위험 등급", "점수 = [손해배상결과.점수, 지재권결과.점수, 해지결과.점수]\n등급 = '높음' if max(점수) >= 4 else ('보통' if max(점수) >= 2 else '낮음')"),
        xgw("Gw_High", "높음?"),
        appr("Approve_Legal", "법무팀 검토", "계약 위험 검토", ["상대방", "손해배상결과", "지재권결과", "해지결과", "등급"],
             [fld("의견", "법무 의견", "text", True), fld("서명가능", "서명 가능", "bool", True)], location="center"),
        ai("Task_Opinion", "의견서 쓰기",
           goal("세 조항의 검토 결과(`손해배상결과`, `지재권결과`, `해지결과`)와 `등급`, 법무 의견(있으면 `의견`)이 있다.",
                "요청자가 읽을 검토 의견서를 쓴다: 요약 → 조항별 위험과 수정 제안 → 결론.",
                "검토 결과에 없는 새 위험을 만들지 않는다.", "- `의견서`: string (markdown)"),
           "llm", {"의견서": "string"}),
        hook("Task_Reply", "의견서 회신", "{회신주소}", body="fields:[요청번호, 등급, 의견서경로]"),
        end("End"),
    ],
    flows=[f("Start", "Task_Extract"), f("Task_Extract", "Gw_Split"), f("Gw_Split", "Call_Damages"), f("Gw_Split", "Call_IP"), f("Gw_Split", "Call_Term"),
           f("Call_Damages", "Gw_Join"), f("Call_IP", "Gw_Join"), f("Call_Term", "Gw_Join"), f("Gw_Join", "Task_Grade"), f("Task_Grade", "Gw_High"),
           f("Gw_High", "Approve_Legal", "등급 == '높음'", "높음"), f("Gw_High", "Task_Opinion", default=True, name="보통·낮음"),
           f("Approve_Legal", "Task_Opinion"), f("Task_Opinion", "Task_Reply"), f("Task_Reply", "End")],
    data=[out("Data_Opinion", "검토 의견서", "Task_Opinion", "계약검토/{요청번호}.md", template="{의견서}", store_as="의견서경로")],
    cases=[Case("표준 계약", {"요청번호": "CR-01", "계약서": "samples/contracts/standard.pdf", "상대방": "가나상사", "회신주소": {"$test_receiver": "reply"}}, {"등급": "낮음"}),
           Case("무제한 배상", {"요청번호": "CR-02", "계약서": "samples/contracts/unlimited_liability.pdf", "상대방": "다라물산", "회신주소": {"$test_receiver": "reply"}},
                {"등급": "높음"}, {"Approve_Legal": {"의견": "배상 한도 조항 추가 필요", "서명가능": False}})],
    called=["bx37_clause_review"],
    features=["같은 공유 BPM 프로세스를 다른 매핑으로 3번 호출", "호출을 병렬로", "리터럴 입력 매핑(`'손해배상'`)", "AI 두 번 — 추출과 작성 사이에 판단(스크립트·결재)"],
    lessons=["호출 셋이 모두 `결과`를 돌려준다. 출력 매핑으로 이름을 나눠야(`손해배상결과` 등) 셋이 따로 남는다 — 프로토타입 사전 점검에서 호출마다 자기 매핑만 들어가고 결과 셋이 다른 이름으로 남는 것을 확인했다. 출력에 적지 않은 변수는 돌아오지 않는다.",
             "같은 AI 태스크(BX-37 `Task_Review`)가 한 실행 안에서 세 번, 서로 다른 입력으로 돈다. 재생 명세는 태스크마다 하나라서, 종류에 따라 달라지는 값은 목표 문장이 아니라 입력으로 받아야 세 조항에 맞게 재생된다 (프로토타입 시나리오 4의 주의).",
             "추출 목표에 「판단하지 않는 것」을 적어 위험 평가는 검토 BPM 프로세스에만 맡긴다."],
))

# ───────────────────────────── BX-37 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-37", file="bx37_clause_review", name="조항 검토 (공유)", dept="운영·법무·IT·고객",
    origin="프로토타입 시나리오 4의 호출 대상", 
    run_location="server", trigger="BPM 프로세스 호출 — BX-30",
    background="조항 원문과 종류를 받아 사내 표준 조항(업무 파라미터)과 비교하고 위험 점수(0~5)와 수정 제안을 돌려준다.",
    why_location="AI만 — 서버.",
    inputs=[("조항", "string", True, "원문"), ("종류", "string", True, "손해배상/지식재산/해지"),
            ("표준조항", "dict", False, "종류별 사내 표준", {"손해배상": "직접 손해에 한하며 계약금액을 한도로 한다", "지식재산": "산출물의 권리는 발주자에게 귀속", "해지": "30일 전 서면 통지"})],
    nodes=[
        start("Start"),
        xgw("Gw_Empty", "조항 있음?"),
        ai("Task_Review", "조항 검토",
           goal("`조항`은 계약서의 `종류` 조항 원문이다. `표준조항[종류]`가 사내 표준이다.",
                "표준과 비교해 위험 점수(0 없음 ~ 5 매우 높음), 이유, 수정 제안 문구를 낸다.",
                "다른 종류의 조항을 평가하지 않는다.", "- `결과`: {점수(int), 이유(string), 제안(string)}"),
           "llm", {"결과": "dict"}),
        script("Task_Missing", "조항 없음", "결과 = dict(점수=3, 이유='조항이 없음', 제안=표준조항[종류])"),
        end("End"),
    ],
    outputs=["결과"],
    flows=[f("Start", "Gw_Empty"), f("Gw_Empty", "Task_Review", "조항 != ''", "있음"), f("Gw_Empty", "Task_Missing", default=True, name="없음"),
           f("Task_Review", "End"), f("Task_Missing", "End")],
    cases=[Case("무제한 배상", {"조항": "을은 갑에게 발생한 모든 손해를 배상한다.", "종류": "손해배상"}, {"결과": {"점수": {"$gte": 4}}}),
           Case("빈 조항", {"조항": "", "종류": "해지"}, {"결과": {"점수": 3}})],
    features=["호출 대상 공유 BPM 프로세스", "빈 입력 가드(게이트웨이)"],
    lessons=["AI 결과는 값이 매번 조금씩 다르다 — 기대 결과에 비교 연산(`{\"$gte\": 4}`)과 부분 일치를 쓴다 (C14 시험 케이스 비교 규칙)."],
))

# ───────────────────────────── BX-31 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-31", file="bx31_request_triage", name="업무 요청 접수·분배", dept="운영·법무·IT·고객",
    origin="프로토타입 example_operator(운영 비서) 확장 → 새로 설계", 
    run_location="server", trigger="메시지 `ops_request` — 사내 요청 메일함·메신저 봇이 보냄",
    background="""
사내 공용 요청 창구(「운영지원」)로 들어오는 자유 형식 요청을 AI가 읽고 종류(장비/권한/시설/기타)와 긴급도를 정해 담당 팀 큐로 보낸다. 판단이 애매하면(AI 확신도 낮음) 사람이 분류한다. 접수 확인을 요청자에게 보낸다.
""",
    why_location="AI·메시지 — 서버.",
    inputs=[("요청번호", "string", True, ""), ("요청자", "string", True, ""), ("본문", "string", True, "")],
    nodes=[
        start("Start", "요청 도착", kind="message", message="ops_request"),
        ai("Task_Classify", "요청 분류",
           goal("`본문`은 직원이 자유롭게 쓴 요청이다.", "종류(장비|권한|시설|기타), 긴급도(높음|보통|낮음), 한 줄 요약, 확신도(0~1)를 낸다.",
                "요청을 직접 처리하거나 해결책을 제시하지 않는다.",
                "- `종류`: string\n- `긴급도`: string\n- `요약`: string\n- `확신도`: number"),
           "llm", {"종류": "string", "긴급도": "string", "요약": "string", "확신도": "number"}),
        xgw("Gw_Confident", "확신?"),
        appr("Approve_Manual", "사람이 분류", "요청 분류", ["본문", "종류", "긴급도", "요약", "확신도"],
             [fld("종류", "종류", "choice", True, ["장비", "권한", "시설", "기타"]), fld("긴급도", "긴급도", "choice", True, ["높음", "보통", "낮음"])], location="center"),
        svc("Task_Ticket", "티켓 만들기", "ticketing", "create_ticket", {"queue": "종류", "priority": "긴급도", "title": "요약", "body": "본문"}, {"티켓번호": "id"}),
        mail("Task_Ack", "접수 확인", ["{요청자}"], "[접수] {요약}", "티켓 {티켓번호}로 접수되었습니다. 담당: {종류} 팀"),
        end("End"),
    ],
    flows=[f("Start", "Task_Classify"), f("Task_Classify", "Gw_Confident"),
           f("Gw_Confident", "Task_Ticket", "확신도 >= 0.8", "확신"), f("Gw_Confident", "Approve_Manual", default=True, name="애매"),
           f("Approve_Manual", "Task_Ticket"), f("Task_Ticket", "Task_Ack"), f("Task_Ack", "End")],
    service_keys={"ticketing": "ops-ticket"}, extensions=[{"id": "ticketing", "version": ">=1,<2"}],
    cases=[Case("노트북 고장", {"요청번호": "R-1", "요청자": "a@example.com", "본문": "노트북 화면이 안 켜져요. 오늘 오후 고객 미팅이 있어요."}, {"종류": "장비", "긴급도": "높음"}),
           Case("애매한 요청", {"요청번호": "R-2", "요청자": "a@example.com", "본문": "그거 좀 봐주세요"}, {"종류": "기타"},
                {"Approve_Manual": {"종류": "기타", "긴급도": "낮음"}})],
    features=["AI 확신도로 사람 개입 여부 결정 (human-in-the-loop)", "결재 칸이 AI 결과 변수를 덮어씀", "티켓 시스템 서비스 앱"],
    lessons=["확신도는 모델의 자기 평가라 믿을 만하지 않다 — 기준값(0.8)은 케이스로 보정하고, 사람 분류 결과를 모아 나중에 기준을 다시 잡는다."],
))

# ───────────────────────────── BX-32 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-32", file="bx32_customer_inquiry", name="고객 문의 답변 초안", dept="운영·법무·IT·고객",
    origin="새로 설계 — 외부 확장(멱등 아님) 예", 
    run_location="server", trigger="메시지 `cs_inquiry` — 외부 고객센터 SaaS의 웹훅",
    background="""
외부 고객센터 SaaS에 문의가 들어오면, 사내 FAQ 검색(내장 확장)으로 근거를 찾고 AI가 답변 초안을 쓴다. 상담원이 초안을 고치거나 승인하면 외부 SaaS에 답변을 등록한다. 외부 SaaS의 「답변 등록」은 멱등이 아니다 — 시간 초과 때 자동 재시도하면 고객에게 답이 두 번 갈 수 있다.
""",
    why_location="외부 API·AI·결재 — 서버.",
    inputs=[("문의번호", "string", True, ""), ("제목", "string", True, ""), ("본문", "string", True, "")],
    nodes=[
        start("Start", "문의 도착", kind="message", message="cs_inquiry"),
        svc("Task_Search", "FAQ 검색", "kb-search", "search", {"query": "본문", "top_k": "5"}, {"근거": "hits"}),
        ai("Task_Draft", "답변 초안",
           goal("`본문`은 고객 문의, `근거`는 사내 FAQ 검색 결과(최대 5개)다.", "근거만 사용해 정중한 답변 초안을 쓴다. 근거가 부족하면 `근거부족`을 true로.",
                "근거에 없는 정책·보상을 약속하지 않는다.", "- `초안`: string\n- `근거부족`: bool"),
           "llm", {"초안": "string", "근거부족": "bool"}),
        appr("Approve_Agent", "상담원 확인", "답변 확인", ["제목", "본문", "초안", "근거부족"],
             [fld("최종답변", "최종 답변", "text", True), fld("보내기", "보내기", "bool", True)], location="center"),
        xgw("Gw_Send", "보내기?"),
        svc("Task_Post", "답변 등록", "ext-helpdesk", "post_reply", {"ticket_id": "문의번호", "body": "최종답변"}, {"등록": "result"}),
        appr("Approve_Check", "등록 여부 확인", "답변 등록 확인", ["문의번호", "최종답변", "error_message"],
             [fld("등록됨", "외부 헬프데스크에 답변이 등록되어 있습니까?", "choice", True, ["등록됨", "안 됨 — 직접 등록함"])], location="center",
             description="등록 응답을 받지 못했습니다. 헬프데스크 화면에서 확인하세요. 자동으로 다시 보내지 않습니다."),
        end("End"),
    ],
    flows=[f("Start", "Task_Search"), f("Task_Search", "Task_Draft"), f("Task_Draft", "Approve_Agent"), f("Approve_Agent", "Gw_Send"),
           f("Gw_Send", "Task_Post", "보내기", "보냄"), f("Gw_Send", "End", default=True, name="보류"), f("Task_Post", "End"),
           f("Bnd_Timeout", "Approve_Check"), f("Approve_Check", "End")],
    boundaries=[bnd("Bnd_Timeout", "Task_Post", "error", "실패·결과 모름", error="TASK_FAILED")],
    service_keys={"kb-search": "cs-kb", "ext-helpdesk": "cs-helpdesk"},
    extensions=[{"id": "kb-search", "version": ">=1,<2"}, {"id": "ext-helpdesk", "version": ">=1,<2"}],
    cases=[Case("배송 문의", {"문의번호": "T-1001", "제목": "배송 언제 와요?", "본문": "주문한 지 5일 지났어요"}, {"근거부족": False},
                {"Approve_Agent": {"최종답변": "안녕하세요 고객님, ...", "보내기": True}})],
    features=["외부 확장 `idempotent:false` 작업 — 자동 재시도 없음", "실패·결과 모름을 오류 경계로 받아 사람 확인 결재로", "RAG형 근거 검색 + 초안", "결재에서 긴 글 수정(text 칸)"],
    lessons=["멱등이 아닌 외부 작업은 C13 정의에 `idempotent:false`로 적는다. 결과를 모르는 실패는 서버에서 실행 실패 또는 오류 경계로 간다 (C13 §4-1) — 이 예제는 오류 경계로 받아 사람이 외부 화면을 확인한다. 기록만 남기고 끝내면 아무도 모른다.",
             "오류 경계는 확실한 실패(4xx)와 결과 모름을 같이 받는다 — 결재 창에 `error_message`를 보여 구분하게 한다.",
             "서버 배포에는 `post_reply`가 결정 수행을 지원해야 한다 (C1 R8). 외부 정의의 `modes`에 명시한다.",
             "AI 초안을 그대로 보내지 않는다 — 고객에게 나가는 글은 사람이 확인."],
))

# ───────────────────────────── BX-33 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-33", file="bx33_access_request", name="IT 권한 신청", dept="운영·법무·IT·고객",
    origin="새로 설계", 
    run_location="server", trigger="메시지 `access_request` — 포털 권한 신청",
    background="""
직원이 시스템 권한을 신청하면 규칙표가 권한 위험도(낮음/중간/높음)와 필요한 결재선을 정한다. 낮음은 팀장만, 중간은 팀장 + 시스템 관리자, 높음은 팀장 + 시스템 관리자 + 보안팀. 결재가 모두 끝나면 디렉터리에 권한을 주고 90일 뒤 자동 회수 일정을 남긴다.
""",
    why_location="결재 여러 단계 — 서버.",
    inputs=[("신청번호", "string", True, ""), ("사번", "string", True, ""), ("시스템", "string", True, ""), ("권한", "string", True, "read/write/admin"), ("사유", "string", True, ""), ("신청자메일", "string", True, "")],
    nodes=[
        start("Start", "권한 신청", kind="message", message="access_request"),
        rule("Task_Risk", "위험도", "access_risk", {"시스템": "시스템", "권한": "권한"}, {"위험도": "risk"}),
        appr("Approve_Lead", "팀장", "권한 신청 (팀장)", ["사번", "시스템", "권한", "사유", "위험도"], [fld("승인", "승인", "bool", True)], location="center"),
        xgw("Gw_Need2", "관리자 결재 필요?"),
        appr("Approve_Owner", "시스템 관리자", "권한 신청 (시스템 관리자)", ["사번", "시스템", "권한", "사유", "위험도"], [fld("승인", "승인", "bool", True)], location="center"),
        xgw("Gw_Need3", "보안팀 결재 필요?"),
        appr("Approve_Sec", "보안팀", "권한 신청 (보안팀)", ["사번", "시스템", "권한", "사유", "위험도"], [fld("승인", "승인", "bool", True), fld("기간", "허용 기간(일)", "number", default=90)], location="center"),
        xgw("Gw_Ok", "모두 승인?"),
        svc("Task_Grant", "권한 부여", "directory", "grant", {"emp_id": "사번", "system": "시스템", "role": "권한"}, {"부여": "result"}),
        svc("Task_Schedule", "회수 예약", "directory", "schedule_revoke", {"emp_id": "사번", "system": "시스템", "after_days": "기간"}, {"예약": "result"}),
        mail("Task_Notify", "결과 안내", ["{신청자메일}"], "[{시스템}] 권한 신청 결과", "승인: {승인}"),
        end("End"),
    ],
    flows=[f("Start", "Task_Risk"), f("Task_Risk", "Approve_Lead"), f("Approve_Lead", "Gw_Need2"),
           f("Gw_Need2", "Approve_Owner", "승인 and 위험도 != '낮음'", "중간 이상"), f("Gw_Need2", "Gw_Ok", default=True, name="낮음·반려"),
           f("Approve_Owner", "Gw_Need3"), f("Gw_Need3", "Approve_Sec", "승인 and 위험도 == '높음'", "높음"), f("Gw_Need3", "Gw_Ok", default=True, name="—"),
           f("Approve_Sec", "Gw_Ok"),
           f("Gw_Ok", "Task_Grant", "승인", "승인"), f("Gw_Ok", "Task_Notify", default=True, name="반려"),
           f("Task_Grant", "Task_Schedule"), f("Task_Schedule", "Task_Notify"), f("Task_Notify", "End")],
    service_keys={"directory": "it-directory"}, extensions=[{"id": "directory", "version": ">=1,<2"}],
    decisions=[Decision("access_risk", "권한 위험도", [("시스템", "시스템", "string"), ("권한", "권한", "string")], [("risk", "string")],
                        [(["-", '"admin"'], ['"높음"'], ""), (['"ERP","HRIS"', '"write"'], ['"높음"'], "재무·인사 쓰기"),
                         (["-", '"write"'], ['"중간"'], ""), (["-", "-"], ['"낮음"'], "")])],
    cases=[Case("위키 읽기", {"신청번호": "AR-1", "사번": "E001", "시스템": "Wiki", "권한": "read", "사유": "문서 열람", "신청자메일": "a@example.com"}, {"위험도": "낮음"},
                {"Approve_Lead": {"승인": True}}),
           Case("ERP 쓰기", {"신청번호": "AR-2", "사번": "E001", "시스템": "ERP", "권한": "write", "사유": "전표 입력", "신청자메일": "a@example.com"}, {"위험도": "높음"},
                {"Approve_Lead": {"승인": True}, "Approve_Owner": {"승인": True}, "Approve_Sec": {"승인": True, "기간": 30}})],
    features=["DMN이 결재선 길이를 정함", "결재 3단계 — 중간 반려 시 바로 끝으로", "기본값 있는 결재 칸(`기간`)"],
    lessons=["`기간`은 보안팀 결재에서만 생긴다 — 낮음·중간이면 `Task_Schedule`이 없는 변수를 읽는다. 실행 전 검사 B11(경로에 따라 없는 변수)이 경고한다. 해결: 시작 직후 스크립트에서 `기간 = 90` 기본값 (이 예제는 일부러 남겨 검사 동작을 보여 줌)."],
))

# ───────────────────────────── BX-34 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-34", file="bx34_incident_alert", name="장애 알림 대응", dept="운영·법무·IT·고객",
    origin="새로 설계", 
    run_location="server", trigger="메시지 `monitor_alert` — 모니터링 시스템 웹훅",
    background="""
모니터링 경보가 오면 AI가 최근 로그 요약과 추정 원인을 정리해 당직자에게 알린다. 당직자가 10분 안에 「확인」하지 않으면 다음 당직자에게, 다시 10분이 지나면 팀장에게 올린다. 모니터링에서 「복구」 메시지가 오면 대응을 끝낸다.
""",
    why_location="빠른 반응·대기 — 서버. 여러 경보가 동시에 들어와도 서버가 병렬로.",
    inputs=[("경보번호", "string", True, ""), ("서비스", "string", True, ""), ("내용", "string", True, ""), ("팀장메일", "string", False, "", "oncall-lead@example.com"),
            ("확인기한", "string", False, "ISO 기간", "PT10M")],
    nodes=[
        start("Start", "경보", kind="message", message="monitor_alert"),
        svc("Task_Logs", "최근 로그", "observability", "recent_logs", {"service": "서비스", "minutes": "15"}, {"로그": "lines"}),
        ai("Task_Summary", "상황 요약",
           goal("`내용`은 경보, `로그`는 최근 15분 로그다.", "무슨 일이 일어나는지 3줄로 요약하고 추정 원인 후보를 최대 3개 적는다.",
                "조치를 실행하지 않는다. 확실하지 않으면 「추정」이라고 적는다.", "- `요약`: string\n- `원인후보`: list"),
           "llm", {"요약": "string", "원인후보": "list"}),
        appr("Approve_Ack1", "1차 당직 확인", "장애 확인 (1차)", ["서비스", "요약", "원인후보"], [fld("확인", "확인함", "bool", True)], location="center"),
        appr("Approve_Ack2", "2차 당직 확인", "장애 확인 (2차)", ["서비스", "요약", "원인후보"], [fld("확인", "확인함", "bool", True)], location="center"),
        mail("Task_Lead", "팀장 호출", ["{팀장메일}"], "[긴급] {서비스} 장애 — 당직 무응답", "{요약}"),
        recv("Recv_Recovered", "복구 기다림", "monitor_recovered", "경보번호"),
        end("End_Lead", "팀장 호출 끝"),
        end("End", "복구"),
    ],
    flows=[f("Start", "Task_Logs"), f("Task_Logs", "Task_Summary"), f("Task_Summary", "Approve_Ack1"),
           f("Approve_Ack1", "Recv_Recovered"), f("Bnd_Ack1", "Approve_Ack2"), f("Approve_Ack2", "Recv_Recovered"),
           f("Bnd_Ack2", "Task_Lead"), f("Task_Lead", "End_Lead"), f("Recv_Recovered", "End")],
    boundaries=[bnd("Bnd_Ack1", "Approve_Ack1", "timer", "확인기한", duration="확인기한"), bnd("Bnd_Ack2", "Approve_Ack2", "timer", "확인기한", duration="확인기한")],
    service_keys={"observability": "ops-observability"}, extensions=[{"id": "observability", "version": ">=1,<2"}],
    cases=[Case("1차 확인 후 복구", {"경보번호": "AL-1", "서비스": "payment-api", "내용": "5xx 비율 12%"}, {"확인": True}, {"Approve_Ack1": {"확인": True}},
                messages=[dict(after_s=10, name="monitor_recovered", correlation="AL-1", payload={})]),
           Case("에스컬레이션", {"경보번호": "AL-2", "서비스": "payment-api", "내용": "5xx 비율 12%", "확인기한": "PT2S"}, {"요약": "*"},
                description="자동 응답 없음 — 2초씩 두 번 지나 팀장 호출로 끝난다")],
    features=["중단 타이머 경계 연쇄(에스컬레이션 사다리)", "결재를 「확인 버튼」으로 쓰기", "받기 태스크로 끝내기"],
    lessons=["확인 기한을 BPMN에 상수(`PT10M`)로 박으면 케이스가 짧게 바꿀 수 없다 — 기본값 있는 입력으로 둔다.",
             "당직 확인 전에 복구 메시지가 오면 받기 태스크가 아직 없어 C12가 `no_receiver`로 거부하고, 실행은 복구를 영원히 기다린다. 메시지 보관(TTL)이 정해지기 전에는 복구 확인을 받기 대신 확인 결재의 칸(「이미 복구됨」)으로도 받는 편이 안전하다 — README 「아직 정하지 않은 것」.",
             "팀장 호출 뒤에도 복구 메시지를 기다리게 하려면 `Task_Lead` → `Recv_Recovered`로 이어도 된다. 끝 이벤트가 둘인 것은 의도."],
))

# ───────────────────────────── BX-35 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-35", file="bx35_voc_weekly", name="VOC 주간 분석", dept="운영·법무·IT·고객",
    origin="새로 설계", 
    run_location="server", trigger="타이머 — 매주 월요일 07:00",
    background="""
지난주 고객 문의·리뷰(수백 건)를 가져와 주제별로 묶고 감성을 매긴 뒤, 경영진용 한 장 요약과 상세 xlsx를 만든다. 건이 많아 50건씩 묶어 병렬로 분석한다.
""",
    why_location="대량 AI 처리 — 서버 병렬.",
    nodes=[
        start("Start", "매주 월요일", kind="timer", cycle="0 7 * * 1"),
        script("Task_Range", "기간 정하기", "시작일 = 날짜더하기(오늘, -7)"),
        svc("Task_Fetch", "지난주 VOC", "ext-helpdesk", "export_tickets", {"since": "시작일"}, {"VOC": "items"}),
        script("Task_Chunk", "50건씩 묶기", "묶음 = 나누기(VOC, 50)"),
        ai("Task_Analyze", "묶음 분석",
           goal("`한묶음`은 고객 문의·리뷰 최대 50건이다.", "건마다 주제(자유 단어 1~2개)와 감성(긍정|중립|부정)을 붙인다.",
                "건을 합치거나 빼지 않는다.", "- `분석`: list of {id, 주제, 감성}"),
           "llm", {"분석": "list"}, loop=dict(collection="묶음", item="한묶음", result="분석", collect_into="분석묶음", parallel=True)),
        script("Task_Merge", "합치고 세기", "전체 = 펼치기(분석묶음)\n주제별 = 세기(전체, '주제')\n부정비율 = 비율(전체, 감성='부정')"),
        ai("Task_Brief", "경영진 요약",
           goal("`주제별` 건수와 `부정비율`, 대표 문의 몇 개가 있다.", "한 장 요약을 쓴다: 이번 주 핵심 3가지, 늘어난 불만, 제안.",
                "숫자를 새로 만들지 않는다.", "- `요약`: string"), "llm", {"요약": "string"}),
        mail("Task_Send", "배포", ["{경영진메일}"], "[VOC 주간] 부정 {부정비율}", "{요약}", attachments=["상세경로"]),
        end("End"),
    ],
    flows=[f("Start", "Task_Range"), f("Task_Range", "Task_Fetch"), f("Task_Fetch", "Task_Chunk"), f("Task_Chunk", "Task_Analyze"), f("Task_Analyze", "Task_Merge"),
           f("Task_Merge", "Task_Brief"), f("Task_Brief", "Task_Send"), f("Task_Send", "End")],
    inputs=[("경영진메일", "list", False, "", ["exec@example.com"])],
    data=[out("Data_Detail", "상세", "Task_Merge", "VOC/{오늘}_상세.xlsx", "xlsx", variables=["전체", "주제별"], store_as="상세경로")],
    service_keys={"ext-helpdesk": "cs-helpdesk-read"}, extensions=[{"id": "ext-helpdesk", "version": ">=1,<2"}],
    cases=[Case("소량 120건", {}, {"분석묶음": ["*", "*", "*"]}, description="모의 SaaS가 120건 → 3묶음")],
    features=["묶음 단위 병렬 AI (비용·시간 조절)", "같은 외부 확장을 읽기 전용 키로 (`cs-helpdesk-read`)", "AI 두 단계 — 대량 분류 → 요약"],
    lessons=["한 건씩 반복하면 LLM 호출이 수백 번 — 묶음으로 나눈다. 묶음 크기는 모델 문맥과 출력 길이로 정한다.",
             "같은 서비스 앱이라도 BPM 프로세스마다 다른 키 참조(읽기 전용 키)를 쓸 수 있다 (ADR-0013 옵션 C)."],
))

# ───────────────────────────── BX-36 ─────────────────────────────
EXAMPLES.append(Example(
    id="BX-36", file="bx36_legacy_migration", name="레거시 화면 데이터 이관", dept="운영·법무·IT·고객",
    origin="프로토타입 데스크톱 작업(work_desktop_ui)·시나리오 3의 교훈 → 새로 설계", 
    run_location="pc", trigger="PC Bot 수동 실행 — 이관 기간에 담당자가 묶음마다",
    background="""
API도 내보내기 기능도 없는 오래된 사내 데스크톱 프로그램에서 고객 카드를 한 장씩 열어 값을 읽고, 새 CRM에 API로 넣는다. 읽기는 화면(PC), 쓰기는 서비스 앱. 화면 모양이 예외적인 카드(필드 누락 등)는 AI 태스크(데스크톱 자율)로 읽는다.
""",
    why_location="데스크톱 화면 읽기 → PC. CRM 쓰기는 같은 BPM 프로세스 안에서 서비스 앱으로 (PC에서도 서비스 앱 호출 가능).",
    inputs=[("고객번호목록", "list", True, "이번 묶음")],
    nodes=[
        start("Start", "묶음 시작"),
        ui("Task_Read", "카드 읽기", "legacy.customer.card",
           [dict(key="search.no", action="fill", value="{번호}"), dict(key="search.go", action="click"),
            dict(key="card.fields", action="read_table", result="카드")],
           loop=dict(collection="고객번호목록", item="번호", result="카드", collect_into="카드목록")),
        script("Task_Split", "예외 카드 고르기", "카드값 = [표를사전(c) for c in 카드목록]\n정상 = [c for c in 카드값 if 빈칸없음(c, ['이름', '연락처', '주소', '등급'])]\n예외번호 = [n for n, c in zip(고객번호목록, 카드값) if not 빈칸없음(c, ['이름', '연락처', '주소', '등급'])]\n수작업 = []"),
        ai("Task_ReadOdd", "예외 카드 읽기 (자율)",
           goal("레거시 고객 관리 프로그램에서 고객번호 `번호`의 카드를 연다. 이 카드는 표준 화면과 모양이 다르다.",
                "이름·연락처·주소·등급을 읽는다.", "어떤 값도 고치지 않는다.", "- `카드`: dict"),
           "desktop", {"카드": "dict"}, loop=dict(collection="예외번호", item="번호", result="카드", collect_into="예외카드")),
        script("Task_OddFail", "예외는 사람에게", "예외카드 = []\n수작업 = 예외번호"),
        svc("Task_Import", "CRM에 넣기", "crm", "upsert_customers", {"customers": "정상 + 예외카드"}, {"넣음": "result"}),
        end("End"),
    ],
    flows=[f("Start", "Task_Read"), f("Task_Read", "Task_Split"), f("Task_Split", "Task_ReadOdd"), f("Task_ReadOdd", "Task_Import"), f("Task_Import", "End"),
           f("Bnd_OddFail", "Task_OddFail"), f("Task_OddFail", "Task_Import")],
    boundaries=[bnd("Bnd_OddFail", "Task_ReadOdd", "error", "재생 실패", error="TASK_FAILED")],
    service_keys={"ui-automation": "it-legacy-ui", "crm": "it-crm"}, extensions=[{"id": "ui-automation", "version": ">=0.4,<0.5"}, {"id": "crm", "version": ">=1,<2"}],
    defaults={"forbidden_actions": ["저장·삭제 버튼을 누르지 않는다"], "desktop": {"app": "CustomerManager"}},
    cases=[Case("5건 묶음", {"고객번호목록": ["C001", "C002", "C003", "C004", "C005"]}, {"넣음": {"count": 5}, "수작업": []})],
    features=["UI 태스크(등록 화면)와 AI 데스크톱 자율 태스크를 한 BPM 프로세스에", "PC BPM 프로세스에서 서비스 앱 호출", "upsert로 재실행 안전"],
    lessons=["프로토타입 시나리오 3에서 데스크톱을 AI가 직접 몰면 자율 388초, 재생 56초였다 — 등록된 화면은 UI 태스크로(LLM 없음), 예외만 AI 태스크로.",
             "운영 Bot은 결정 수행(재생)이다. 모양이 제각각인 예외 카드는 재생 명세가 맞지 않을 수 있다 — 그때 운영에서 몰래 자율 수행으로 넘어가지 않는다(ADR-0010). 오류 경계로 받아 `수작업` 목록으로 사람에게 넘기고, 정상 카드는 그대로 넣는다.",
             "`read_table`은 표의 머리글·줄을 돌려준다 (C10). 카드처럼 「항목 | 값」 격자는 표로 읽고 스크립트에서 사전으로 바꾼다."],
))
